// Autogenerated by grunt globaltsd task. Changes to this file will be overwritten
export import container = require ('./client/container')
export import FullScreenFrame = require ('./client/FullScreenFrame')
export import router = require ('./client/router')
export import singlePageContainer = require ('./client/singlePageContainer')
export import Skin = require ('./client/Skin')
