// Autogenerated by grunt globaltsd task. Changes to this file will be overwritten
export import ClientUtils = require ('./webserver/ClientUtils')
export import Endpoint = require ('./webserver/Endpoint')
export import module = require ('./webserver/module')
export import NineplateResource = require ('./webserver/NineplateResource')
export import SinglePage = require ('./webserver/SinglePage')
export import StaticResource = require ('./webserver/StaticResource')
export import WebServer = require ('./webserver/WebServer')
