define({
	alwaysFalse : 'SIEMPRE FALSO',
	alwaysTrue : 'SIEMPRE VERDADERO',
	ambiguousExpression: 'CONDICION AMBIGUA',
	and : 'Y',
	averageOf : 'El promedio de',
	contains : 'Contiene',
	countOf : 'La cantidad de',
	endsWith : 'Termina con',
	equals : 'Igual a',
	every : 'Todos',
	greaterThan : 'Mayor que',
	greaterThanOrEquals : 'Mayor o igual que',
	invalidExpression : 'CONDICION INCOMPLETA',
	lessThan : 'Menor que',
	lessThanOrEquals : 'Menor o igual que',
	not : 'NO',
	notEquals : 'Diferente a',
	or : 'O',
	some : 'Algún',
	startsWith : 'Inicia con',
	sumOf : 'La suma de',
	valueOf : 'El valor de',
	whereCaps: 'CUANDO'
});
