define({
	root: {
		addNewCondition: 'Add new condition',
		addOperation: 'Add Operation',
		advanced: 'Advanced',
		advancedConfigurationOptionsMessage: 'Select the options that best fits your style or your need to control the condition\'s behavior',
		advancedModeMessage: 'The user can create condition elements at will, then completes and groups conditions as he sees fit',
		allCustomCase: 'I want to be able to control all boolean modifiers in the expression',
		allNegativeCase: 'This whole expression is negative',
		allPositiveCase: 'This whole expression is positive',
		and: 'AND',
		averageOf: 'The average of',
		avoidsSyntaxErrors: 'Helps the user to avoid making syntax errors while building the condition',
		cancel: 'Cancel',
		clear: 'Clear',
		clickToAddSubExpression: 'Click here to add a filter to this summary function',
		close: 'Close',
		conditionsEvaluation: 'Condition\'s evaluation',
		conditionsEvaluationDescription: 'This condition will apply when it\'s result is:',
		configurationModes: 'Configuration Modes',
		configurationOptions: 'Configuration Options',
		contains: 'Contains',
		copy: 'Copy',
		countOf: 'The count of',
		degroup: 'Ungroup',
		deleteThis: 'Delete',
		endsWith: 'Ends with',
		equals: 'Equals',
		every: 'Every',
		expertUser: 'Expert user',
		falseF: 'False',
		greaterThan: 'Greater than',
		greaterThanOrEquals: 'Greater or equal than',
		group2: 'Group',
		helpText: 'Please select an expression type in order to start with the creation of a condition',
		iWillControl: 'I\'ll control when each applies',
		lessThan: 'Less than',
		lessThanOrEquals: 'Less or equal than',
		negativeTooltipMessage: 'This is a negative expression. Click here if you want to make it positive',
		noOperators: 'No Operator',
		notEquals: 'Not Equals',
		noValue: 'No Value',
		save: 'Save',
		or: 'OR',
		paste: 'Paste',
		positiveTooltipMessage: 'This is a positive expression. Click here if you want to make it negative',
		redo: 'Redo',
		resetThis: 'Clear',
		select: 'Select',
		selectField: 'Select Field',
		some: 'Some',
		startsWith: 'Starts with',
		strictMode: 'Strict Mode: New expressions are not allowed until this expression becomes valid (<b>recommended</b>)',
		sumOf: 'The sum of',
		trueF: 'True',
		undo: 'Undo',
		unRestrictedMode: 'Unrestricted Mode: New expressions are allowed',
		userGuidedStepByStep: 'User is guided step by step (recommended)',
		valueOf: 'The value of',
		whereCaps: 'WHERE',
		withYourSelection: 'With your selection...'

	},

	es: true,
	en: true,
	fr: true

});
