define({
	addNewCondition: 'Nueva condición',
	addOperation: 'Agregar Operación',
	advanced: 'Avanzado',
	advancedConfigurationOptionsMessage: 'Seleccione las opciones que se ajusten a su estilo o la necesidad de controlar el comportamiento de las condiciones',
	advancedModeMessage: 'El usuario dispone de la creación de los elementos de las condiciones basado en su lógica y luego completa o agrupa las condiciones a discreción',
	allCustomCase: 'Deseo controlar la afirmación o negación de cada expresión individualmente',
	allNegativeCase: 'Esta expresión evalúa si no se cumple (Negativa)',
	allPositiveCase: 'Esta expresión evalúa si se cumple (Positiva)',
	and: 'Y',
	averageOf: 'El promedio de',
	avoidsSyntaxErrors: 'Evita que el usuario cometa errores de sintaxis al crear la condición',
	cancel: 'Cancelar',
	clear: 'Limpiar',
	clickToAddSubExpression: 'Hacer click aquí para agregar un filtro a la agrupación',
	close: 'Cerrar',
	conditionsEvaluation: 'Evaluación de las condiciones',
	conditionsEvaluationDescription: 'La condición aplicará cuando su evaluación resulte:',
	configurationModes: 'Modalidades de configuración',
	configurationOptions: 'Opciones de Configuración',
	contains: 'Contiene',
	copy: 'Copy',
	countOf: 'La cantidad de',
	degroup: 'Desagrupar',
	deleteThis: 'Eliminar',
	endsWith: 'Termina con',
	equals: 'Igual a',
	every: 'Todos',
	expertUser: 'Usuario experto',
	falseF: 'Falsa',
	greaterThan: 'Mayor que',
	greaterThanOrEquals: 'Mayor o igual que',
	group2: 'Agrupar',
	helpText: 'Para iniciar con la creación de la condición, seleccione el criterio de la condición.',
	iWillControl: 'Yo controlaré cuando se aplica cada una',
	lessThan: 'Menor que',
	lessThanOrEquals: 'Menor o igual que',
	negativeTooltipMessage: 'Esta expresión está negada. Click aquí si desea afirmarla',
	noOperators: 'Sin operador',
	notEquals: 'Diferente a',
	noValue: 'Sin valor',
	save: 'Guardar',
	or: 'O',
	paste: 'Paste',
	positiveTooltipMessage: 'Esta expresión está afirmada. Click aquí si desea negarla',
	redo: 'Rehacer',
	resetThis: 'Reiniciar',
	select: 'Seleccionar',
	selectField: 'Seleccionar Campo',
	some: 'Algún',
	startsWith: 'Inicia con',
	strictMode: 'Modo estricto: Nuevas expresiones no serán permitidas hasta tanto esta expresión sea válida (<b>recomendado</b>)',
	sumOf: 'La suma de',
	trueF: 'Verdadera',
	undo: 'Deshacer',
	unRestrictedMode: 'Modo sin restricción: Nuevas expresiones serán permitidas',
	userGuidedStepByStep: 'Usuario es guiado paso a paso (Recomendado)',
	valueOf: 'El valor de',
	whereCaps: 'CUANDO',
	withYourSelection: 'Con su selección...'
});
