// Autogenerated by grunt globaltsd task. Changes to this file will be overwritten
export import nodeXml = require ('./node/node-xml')
export import text = require ('./node/text')
export import xmlParser = require ('./node/xmlParser')
