// Autogenerated by grunt globaltsd task. Changes to this file will be overwritten
export import append = require ('./utils/append')
export import domUtils = require ('./utils/domUtils')
export import setClass = require ('./utils/setClass')
export import setText = require ('./utils/setText')
